### PR TITLE
Update pt_BR.json

### PR DESCRIPTION
**Pull request by maisondasilva**

### CODE REVIEW

**Comment by countrystarter2334** [comment]
hey i am new here and i do not know what to do

**Comment by alexmercerind** [comment]
> hey i am new here and i do not know what to do

We need updates to the translation file. A lot of strings are altered/changed in english (e.g. capitalization & meaning etc.).
Another look will be helpful.

A lot of features are unstaged right now & will be available in next release.

English Text: https://github.com/harmonoid/harmonoid/blob/master/assets/translations/en_US.json
Equivalent Portuguese (Brazil): https://github.com/harmonoid/harmonoid/blob/master/assets/translations/pt_BR.json

For getting started with minimal pull requests, just click pencil icon in the top-right of above Portuguese link.

**Comment by maisondasilva** [comment]
If she understands Portuguese can help us in the next translation. In the request above translated all current variables @alexmercerind

**Comment by alexmercerind** [comment]
> If she understands Portuguese can help us in the next translation. In the request above translated all current variables @alexmercerind

Sorry for the delay. My local tree is having a lot of upstaged changes. Now I have time to look for public pull-requests.

We need a lot of updates. e.g. capitalization is changed at the lot of places (and other strings' meaning has been updated too).

For example:

https://github.com/harmonoid/harmonoid/blob/2b26689a508dcf2b9ec845a38ffe57e837cecb09/assets/translations/en_US.json#L116
https://github.com/harmonoid/harmonoid/blob/2b26689a508dcf2b9ec845a38ffe57e837cecb09/assets/translations/pt_BR.json#L116

I'd be greatly helped by another look from you. Thanks for the PR!

**Pull request merged**
