### PR TITLE
Update ru_RU.json

### PR DESCRIPTION
**Pull request by Feelogil**
- ~~S.F.T.~~
- B.S.T.

### CODE REVIEW

**Comment by alexmercerind** [comment]
Thanks! Should I merge it or is it still a draft?

**Comment by Feelogil** [comment]
no i had to go.

**Comment by alexmercerind** [comment]
there are still few untranslated strings. would you mind taking care of those, or do i merge it as is for now?

**Comment by Feelogil** [comment]
I'm sorry, I'm at work at the moment😒... I can't do anything right now.

**Comment by raitonoberu** [comment]
I've translated the rest of the file & fixed some errors comparing with the original file. This can be merged now, I think,

**Comment by alexmercerind** [comment]
Feel free to do so!

**Pull request merged**
