### PR TITLE
Minor update to CI

### PR DESCRIPTION
**Pull request by prateekmedia**
Looks like I can't create branches in this repo so I pushed to mine first.

Previously icons were not showing up and reporting below error
```
WARNING: No icons found at "usr/share/icons"
WARNING: Using .DirIcon as default app icon
ERROR: Entry doesn't exists: .DirIcon
ERROR: No icon was generated for: /home/prateeksu/Applications/harmonoid_976d4fe7e3c6a21e783cf213a8036f86.AppImage
WARNING: Unable to resize the application icon into a 128x128 image: "Unable to load image.". It will be written unchanged.
WARNING: Unable to resize the application icon into a 256x256 image: "Unable to load image.". It will be written unchanged.
which: no gtk-update-icon-cache-3.0 in (/home/prateeksu/.local/bin:/usr/local/bin....
```

Now above error is fixed

### CODE REVIEW

**Comment by prateekmedia** [comment]
I can't reopen this PR cause the repository was deleted.

**Comment by mytja** [comment]
> I can't reopen this PR cause the repository was deleted.

You can try to recover repository using following technique:
GitHub Settings -> Repository -> Deleted repositories

From there you should be able to recover it

**Comment by prateekmedia** [comment]
@mytja  
```
No recoverable repositories were found for prateekmedia.

It may take up to an hour for repositories to be displayed here. You can only restore repositories that have no forks or have not been forked. Learn more
```

This was the message shown when going there.

**Comment by prateekmedia** [comment]
@mytja I will try to pull it from the commit sha as it doesn't get deleted.

**Pull request closed without merging**
