### PR TITLE
Update hindi translations

### PR DESCRIPTION
**Pull request by prateekmedia**
I have kept some strings untouched as I wasn't sure if they fitted well with the translations but I have updated others which were left at the bottom. Also does this count for hacktoberfest?

प्रेरणादायक गुड नाइट/शुभ रात्रि।

### CODE REVIEW

**Comment by alexmercerind** [comment]
Thanks for updating these. Technically this should count, since I added `hacktoberfest` tag to the repository.
Harmonoid welcomes any kind of meaningful or constructive contribution. ✨

**Comment by prateekmedia** [comment]
@alexmercerind I think `hacktoberfest-accepted` label was also required before merging the PR?

**Comment by alexmercerind** [comment]
> Update 10/5/20: PRs can now be made in any participating GitHub-hosted repository/project. Your PRs will count toward your participation if they are in a repo with the `hacktoberfest` topic and once they have been merged, approved by a maintainer, or labeled as `hacktoberfest-accepted`.

I assume not having label in PR will still work.

Reference: [here](https://dev.to/devteam/an-update-on-hacktoberfest-37a).

**Comment by alexmercerind** [comment]
I added the label regardless. I think their ruby script will acknowledge this.

**Pull request merged**
