### PR TITLE
Fix rpm package

### PR DESCRIPTION
**Pull request by prateekmedia**
Remove alien and switch to rpm spec build, #132

### CODE REVIEW

**Comment by alexmercerind** [comment]
Thanks a lot for your contributions over time, currently repository isn't in very pleasant state. I'm working on some big changes & refactor. We will be ready soon. It will require minor changes in compilation instructions aswell.

Thankyou,

**Comment by alexmercerind** [comment]
Hey @prateekmedia!

We recently created a Discord sever, it would be great for us to see you join!

There's an invite link in the README.

**Comment by prateekmedia** [comment]
@alexmercerind I might do that but I don't use discord, Also I have updated the PR.

**Comment by prateekmedia** [comment]
This needs to be updated, you can tell me when linux is stable I will push an updated PR.

**Comment by alexmercerind** [comment]
@prateekmedia my man seems it's the time.
We should keep `libmpv-dev` (or equivalnt) on consumer's machine.

**Comment by prateekmedia** [comment]
@alexmercerind I think it's ready for review, also if you are using mpris and it is also needed for building then you can add it to apt-get, Idk much about that part.

**Comment by prateekmedia** [comment]
If yes then we have to add `Requires:` clause in the spec file for it

**Comment by alexmercerind** [comment]
I think we should add `libmpv-dev` anyway, since I noticed that my `mpv` was updated but it still kept using old `libmpv` because my `libmpv-dev` was older from another PPA.

**Comment by prateekmedia** [comment]
@alexmercerind mpv or mpv-libs-devel is not in the main fedora repo, hence anyone installing this app needs to have RPM FUSION repository added(the popular third party repo).

More on this here: https://www.reddit.com/r/Fedora/comments/m6d9xs/where_is_mpv/

**Comment by alexmercerind** [comment]
Thanks for the awesome work man! 💙

**Pull request merged**
